add 2 GET methods from notifications GitHub API & bump clj-http to 2.1.0
Raynes/tentacles pull request #93
Opened 2016-02-27 20:21 UTC by vyorkin

add 2 GET methods from here https://developer.github.com/v3/activity/notifications/ and bump clj-http to 2.1.0

2016-02-27 20:22 UTC, vyorkin commented on src/tentacles/notifications.clj
> +(defn repo-notifications
not sure it belongs here though, maybe it should go into tentacles.repos

2016-10-26 02:22 UTC, Raynes approved these changes

2016-10-26 02:24 UTC, Raynes requested changes
This has to go because we did it already.

2017-03-18 08:32 UTC, jjl commented
merged in my fork: [irresponsible/tentacles](https://github.com/irresponsible/tentacles) (well, copied and pasted because of Raynes' revisions)

more info here: https://groups.google.com/forum/#!topic/clojure/UJetyHj-BPE

2017-06-24 00:19 UTC, closed without merging